apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: bigquerydatasetsample
spec:
  defaultTableExpirationMs: 3600000
  description: "BigQuery Dataset Sample123"
  friendlyName: bigquerydataset-sample123
  location: US